# Generated by Django 5.2.5 on 2025-08-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                ("productid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderList",
            fields=[
                ("orderid", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "order_state",
                    models.IntegerField(
                        choices=[(0, "Paid"), (1, "Unpaid")], default=1
                    ),
                ),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productlist",
                    ),
                ),
            ],
        ),
    ]
