# Generated by Django 5.2.5 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_orderlist_productid_remove_orderlist_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="final_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="voucher_discount",
            field=models.FloatField(default=0),
        ),
    ]
